#!/bin/sh
# This script ensures that the test data is owned by root.

set -e

rm -rf test/testdata
mkdir test/testdata
cp -r ${srcdir}/test/*.ex* test/testdata
mkdir test/testdata/run-parts.ex2
chown -R root:root test/testdata
