#!/bin/sh
if [ -d m4 ]; then
  :
else
  mkdir m4
fi
if [ -d scripts ]; then
  :
else
  mkdir scripts
fi
sed -e "s/@RELEASE_DATE@/`date '+%d %b %Y'`/" -e "s/@RELEASE_UDATE@/`date '+%s'`/" scripts/schroot_release.m4.in > m4/schroot_release.m4

# To satisfy automake
touch ChangeLog


echo "libtoolize"
libtoolize --force --copy
echo "autopoint"
autopoint --force
echo "aclocal -I m4"
aclocal -I m4
echo "autoheader"
autoheader
echo "automake"
automake --add-missing --gnu --force --copy
echo "autoconf"
autoconf

rm -rf autom4te.cache/

