#!/bin/sh
# Copyright © 2005-2010  Roger Leigh <rleigh@debian.org>
#
# schroot is free software: you can redistribute it and/or modify it
# under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# schroot is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see
# <http://www.gnu.org/licenses/>.
#
#####################################################################

set -e

if [ -f "$CHROOT_SCRIPT_CONFIG" ]; then
    . "$CHROOT_SCRIPT_CONFIG"
elif [ "$2" = "ok" ]; then
    echo "script-config file '$CHROOT_SCRIPT_CONFIG' does not exist"
    exit 1
fi

if [ "$AUTH_VERBOSITY" = "verbose" ]; then
  VERBOSE="-v"
fi

if [ "$CHROOT_TYPE" = "btrfs-snapshot" ]; then

    if [ $1 = "setup-start" ]; then

	if [ "$AUTH_VERBOSITY" = "verbose" ]; then
	    echo "Creating snapshot $CHROOT_BTRFS_SNAPSHOT_NAME from subvolume $CHROOT_BTRFS_SOURCE_SUBVOLUME"
	fi

	if [ "$AUTH_VERBOSITY" = "verbose" ]; then
	    btrfs subvolume snapshot "$CHROOT_BTRFS_SOURCE_SUBVOLUME" \
		"$CHROOT_BTRFS_SNAPSHOT_NAME"
	else
	    btrfs subvolume snapshot "$CHROOT_BTRFS_SOURCE_SUBVOLUME" \
		"$CHROOT_BTRFS_SNAPSHOT_NAME" > /dev/null
	fi

    elif [ $1 = "setup-stop" ]; then

	if [ -d "$CHROOT_BTRFS_SNAPSHOT_NAME" ]; then

	    if [ "$AUTH_VERBOSITY" = "verbose" ]; then
		echo "Deleting snapshot $CHROOT_BTRFS_SNAPSHOT_NAME"
	    fi

	    if [ "$AUTH_VERBOSITY" = "verbose" ]; then
		btrfs subvolume delete "$CHROOT_BTRFS_SNAPSHOT_NAME" || true
	    else
		btrfs subvolume delete "$CHROOT_BTRFS_SNAPSHOT_NAME" > /dev/null || true
	    fi

	else
	    # The block device no longer exists, or was never created,
	    # for example on lvcreate failure.
	    if [ "$AUTH_VERBOSITY" = "verbose" ]; then
		echo "$CHROOT_BTRFS_SNAPSHOT_NAME does not exist"
	    fi
	fi

    fi

fi

