#!/bin/sh

TAG="$(git describe --abbrev=0 --match='release/*')"
PKGVER="${TAG#release/}"
PACKAGE="$(echo "$PKGVER" | sed -e 's/^\([^-]*\)-\(.*\)$/\1/')"
VERSION="$(echo "$PKGVER" | sed -e 's/^\([^-]*\)-\(.*\)$/\2/')"
COMMIT="$(git rev-parse "$TAG^{}")"
COMMIT_DATE="$(git log -1 --date=iso "$COMMIT" --pretty="format:%ad")"

RELEASE_DATE="$(date --date="$COMMIT_DATE" '+%d %b %Y')"
RELEASE_BY="$(git show "$TAG" | sed -ne '/^Tagger:/{s/Tagger:[[:space:]][[:space:]]*//p;q}')"

echo "Package: $PACKAGE"
echo "Version: $VERSION"
echo "Release-Date: $RELEASE_DATE"
echo "Released-By: $RELEASE_BY"
echo "Git-Tag: $TAG"
