#!/bin/sh

if [ $1 = "setup-start" ]; then

    if [ "$AUTH_VERBOSITY" = "verbose" ]; then
	echo "AUTH_USER=$AUTH_USER"
	echo "AUTH_VERBOSITY=$AUTH_VERBOSITY"
	echo "MOUNT_DIR=$MOUNT_DIR"
	echo "LIBEXEC_DIR=$LIBEXEC_DIR"
	echo "PID=$PID"
	echo "SESSION_ID=$SESSION_ID"
	echo "CHROOT_TYPE=$CHROOT_TYPE"
	echo "CHROOT_NAME=$CHROOT_NAME"
	echo "CHROOT_DESCRIPTION=$CHROOT_DESCRIPTION"
	echo "CHROOT_MOUNT_LOCATION=$CHROOT_MOUNT_LOCATION"
	echo "CHROOT_MOUNT_DEVICE=$CHROOT_MOUNT_DEVICE"
	if [ "$CHROOT_TYPE" = "plain" ]; then
	    echo "CHROOT_LOCATION=$CHROOT_LOCATION"
	elif [ "$CHROOT_TYPE" = "block-device" -o "$CHROOT_TYPE" = "lvm-snapshot" ]; then
	    echo "CHROOT_DEVICE=$CHROOT_DEVICE"
	    echo "CHROOT_MOUNT_OPTIONS=$CHROOT_MOUNT_OPTIONS"
	    if [ "$CHROOT_TYPE" = "lvm-snapshot" ]; then
		echo "CHROOT_LVM_SNAPSHOT_NAME=$CHROOT_LVM_SNAPSHOT_NAME"
		echo "CHROOT_LVM_SNAPSHOT_DEVICE=$CHROOT_LVM_SNAPSHOT_DEVICE"
		echo "CHROOT_LVM_SNAPSHOT_OPTIONS=$CHROOT_LVM_SNAPSHOT_OPTIONS"
	    fi
	fi
    fi

    case "$CHROOT_TYPE" in
	plain)
	    if [ ! -d "$CHROOT_LOCATION" ]; then
		echo "$CHROOT_LOCATION does not exist"
		exit 1
	    fi
	    ;;
	block-device | lvm-snapshot)
	    if [ ! -b "$CHROOT_DEVICE" ]; then
		echo "$CHROOT_DEVICE does not exist"
		exit 1
	    fi
	    ;;
	*)
	    echo "Unknown chroot type $CHROOT_TYPE"
	    exit 1
	    ;;
    esac

    if [ -z "$CHROOT_MOUNT_LOCATION" -o "$CHROOT_MOUNT_LOCATION" = "/" ]; then
	echo "Invalid chroot mount location: '$CHROOT_MOUNT_LOCATION'"
	exit 1
    fi

fi
