#!/bin/sh

set -e

# Check file type
check_filetype()
{
    if echo "$CHROOT_FILE" | grep -q '.tar$'; then
	filetype="tar"
    elif echo "$CHROOT_FILE" | egrep -q '(.tar.gz|.tgz)$'; then
	filetype="tgz"
    elif echo "$CHROOT_FILE" | egrep -q '(.tar.bz2|.tbz)$'; then
	filetype="tbz"
    elif echo "$CHROOT_FILE" | grep -q '.zip$'; then
	filetype="zip"
    else
	echo "Unsupported filetype for $CHROOT_FILE"
	exit 1
    fi
}

# Unpack archive
unpack_file()
{
	if [ "$filetype" = "tar" ]; then
	    tar $VERBOSE -xf "$CHROOT_FILE"
	elif [ "$filetype" = "tgz" ]; then
	    tar $VERBOSE -xzf "$CHROOT_FILE"
	elif [ "$filetype" = "tbz" ]; then
	    tar $VERBOSE -xzf "$CHROOT_FILE"
	elif [ "$filetype" = "zip" ]; then
	    unzip $ZIP_VERBOSE "$CHROOT_FILE"
	else
	    echo "Unsupported filetype for $CHROOT_FILE"
	    exit 1
	fi
}

if [ "$AUTH_VERBOSITY" = "verbose" ]; then
    VERBOSE="-v"
else
    ZIP_VERBOSE="-q"
fi

if [ "$CHROOT_TYPE" = "file" ]; then

    if [ $1 = "setup-start" ]; then

	check_filetype

        if [ ! -d "$CHROOT_MOUNT_LOCATION" ]; then
	    mkdir -p "$CHROOT_MOUNT_LOCATION"
        fi
	cd "$CHROOT_MOUNT_LOCATION"

	unpack_file

    elif [ $1 = "setup-stop" ]; then

	rm -rf "$CHROOT_MOUNT_LOCATION" || true

    fi

fi

