#!/bin/sh

set -e

# Check file type
check_filetype()
{
    if echo "$CHROOT_FILE" | grep -q '\.tar$'; then
	filetype="tar"
    elif echo "$CHROOT_FILE" | egrep -q '(\.tar\.gz|\.tgz)$'; then
	filetype="tgz"
    elif echo "$CHROOT_FILE" | egrep -q '(\.tar\.bz2|\.tbz)$'; then
	filetype="tbz"
    elif echo "$CHROOT_FILE" | grep -q '\.zip$'; then
	filetype="zip"
    else
	echo "Unsupported filetype for $CHROOT_FILE"
	exit 1
    fi
}

# Unpack archive
unpack_file()
{
    if [ "$filetype" = "tar" ]; then
	tar $VERBOSE -xf "$CHROOT_FILE"
    elif [ "$filetype" = "tgz" ]; then
	tar $VERBOSE -xzf "$CHROOT_FILE"
    elif [ "$filetype" = "tbz" ]; then
	tar $VERBOSE -xjf "$CHROOT_FILE"
    elif [ "$filetype" = "zip" ]; then
	unzip $ZIP_VERBOSE "$CHROOT_FILE"
    else
	echo "Unsupported filetype for $CHROOT_FILE"
	exit 1
    fi
}

# Repack archive
repack_file()
{
    NEWFILE=`mktemp "${CHROOT_FILE}.XXXXXX"`

    trap "if [ -f \"$NEWFILE\" ]; then rm -f \"$NEWFILE\"; fi" 0

    if [ "$filetype" = "tar" ]; then
	tar $VERBOSE -cf "$NEWFILE" .
    elif [ "$filetype" = "tgz" ]; then
	tar $VERBOSE -czf "$NEWFILE" .
    elif [ "$filetype" = "tbz" ]; then
	tar $VERBOSE -cjf "$NEWFILE" .
    elif [ "$filetype" = "zip" ]; then
	zip $ZIP_VERBOSE -r "$NEWFILE" .
    else
	echo "Unsupported filetype for $CHROOT_FILE"
	exit 1
    fi

    mv "$NEWFILE" "$CHROOT_FILE"

    trap "" 0
}

if [ "$AUTH_VERBOSITY" = "verbose" ]; then
    VERBOSE="-v"
else
    ZIP_VERBOSE="-q"
fi

if [ "$CHROOT_TYPE" = "file" ]; then

    check_filetype

    if [ $1 = "setup-start" ]; then

        if [ ! -d "$CHROOT_MOUNT_LOCATION" ]; then
	    mkdir -p "$CHROOT_MOUNT_LOCATION"
        fi
	cd "$CHROOT_MOUNT_LOCATION"

	unpack_file

    elif [ "$1" = "setup-stop" ]; then

	if [ "$2" = "ok" ] && [ "$CHROOT_FILE_REPACK" = "true" ]; then
	    cd "$CHROOT_MOUNT_LOCATION" && repack_file
	fi

	rm -rf "$CHROOT_MOUNT_LOCATION" || true

    fi

fi

