#!/bin/sh

if [ "$AUTH_VERBOSITY" = "verbose" ]; then
  VERBOSE="--verbose"
fi

if [ $1 = "setup-start" -o $1 = "setup-recover" ]; then
  cp $VERBOSE /etc/resolv.conf "${CHROOT_PATH}/etc/resolv.conf"
fi

