#!/bin/sh

if [ "$AUTH_VERBOSITY" = "verbose" ]; then
  VERBOSE="--verbose"
fi

if [ $1 = "start" ]; then
  cp $VERBOSE /etc/passwd "${CHROOT_LOCATION}/etc/passwd"
  cp $VERBOSE /etc/shadow "${CHROOT_LOCATION}/etc/shadow"
  cp $VERBOSE /etc/group  "${CHROOT_LOCATION}/etc/group"
fi

